sudo: required
dist: trusty
language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - nightly

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=oauth2
  matrix:
    - DB=sqlite

matrix:
    include:
      - php: 5.6
        env: DB=oracle
      - php: 5.6
        env: DB=mysql
      - php: 5.6
        env: DB=pgsql
      - php: 5.6
        env: DB=mysqlmb4
    allow_failures:
      - php: nightly
    fast_finish: true

branches:
  only:
    - master
    - /^stable\d*$/

before_install:
    # enable a display for running JavaScript tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - nvm install 5.9
    - npm install -g npm@latest
    - make
    - make appstore
    # install core
    - bash tests/.travis/before_install.sh $APP_NAME $CORE_BRANCH $DB
    # Add some output debugging information
    - cd ../core
    - ./occ app:enable $APP_NAME
    - ./occ check
    - ./occ status
    - ./occ app:list

before_script:
    - php -S localhost:8080 &
    - cd apps/$APP_NAME

script:
    - make test

after_failure:
    - cat ../../data/owncloud.log

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
    firefox: "latest"
